---
# Source: prometheus/templates/server/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: simple-prometheus-server-headless
  namespace: application
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090

  selector:
    app: prometheus
